# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import image_action_pb2 as image__action__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in image_action_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImageActionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageActionStream = channel.stream_stream(
                '/imageaction.ImageActionService/ImageActionStream',
                request_serializer=image__action__pb2.ImageMessage.SerializeToString,
                response_deserializer=image__action__pb2.ActionMessage.FromString,
                _registered_method=True)


class ImageActionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageActionStream(self, request_iterator, context):
        """双向流：客户端发送图片，服务器接收并发送动作指令
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageActionStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ImageActionStream,
                    request_deserializer=image__action__pb2.ImageMessage.FromString,
                    response_serializer=image__action__pb2.ActionMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageaction.ImageActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('imageaction.ImageActionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImageActionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageActionStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/imageaction.ImageActionService/ImageActionStream',
            image__action__pb2.ImageMessage.SerializeToString,
            image__action__pb2.ActionMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
